### Get all tasks
GET http://localhost:3001/tasks

### Add a new task
POST http://localhost:3001/tasks
Content-Type: application/json

{
    "description": "New task from REST client"
}
### Delete task
DELETE http://localhost:3001/delete/1 HTTP/1.1
